const jCategory = [
    {
        index: 0,
        image: "../images/google.png",
        title: "Web Developer",
        rate: '$900-1200/m',
        av: "Full Time",
        companyName: "Google",
        location: "USA",
        vacancy: "01",
        hours: "50h / Week",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis, sunt aut odit voluptatibus accusantium sed iste ipsum voluptas error similique enim sequi ea! Sed officia tenetur, commodi provident possimus a sapiente? Ducimus repudiandae illum porro? Fugiat sed facilis iusto sapiente aperiam ratione ut sequi laborum laboriosam, optio soluta consequatur perferendis praesentium! Inventore exercitationem ullam accusantium incidunt sit pariatur facilis asperiores natus excepturi quos esse quidem eos odit dolores fuga ipsum reprehenderit cupiditate deleniti deserunt, debitis vel voluptate ducimus. Error tempora necessitatibus repudiandae vero ullam illum vel quisquam corporis hic voluptatem sit pariatur minus corrupti inventore, adipisci ex unde esse quaerat. Est, illum voluptates aut cumque id hic placeat sunt natus, non iusto ea aliquam dignissimos quas accusantium assumenda eius minus.",
        workplace: "On-site",
        education: "Bachelor degree in any Computer Science.",
        experience: "2 to 5 year(s)"
    },
    {
        index: 1,
        image: "../images/uber.png",
        title: "Business Associate",
        rate: '$900-1200/m',
        av: "Part Time",
        companyName: "Uber",
        location: "USA",
        vacancy: "04",
        hours: "40h / Week",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis, sunt aut odit voluptatibus accusantium sed iste ipsum voluptas error similique enim sequi ea! Sed officia tenetur, commodi provident possimus a sapiente? Ducimus repudiandae illum porro? Fugiat sed facilis iusto sapiente aperiam ratione ut sequi laborum laboriosam, optio soluta consequatur perferendis praesentium! Inventore exercitationem ullam accusantium incidunt sit pariatur facilis asperiores natus excepturi quos esse quidem eos odit dolores fuga ipsum reprehenderit cupiditate deleniti deserunt, debitis vel voluptate ducimus. Error tempora necessitatibus repudiandae vero ullam illum vel quisquam corporis hic voluptatem sit pariatur minus corrupti inventore, adipisci ex unde esse quaerat. Est, illum voluptates aut cumque id hic placeat sunt natus, non iusto ea aliquam dignissimos quas accusantium assumenda eius minus.",
        workplace: "On-site",
        education: "Bachelor degree in any Computer Science.",
        experience: "2 to 5 year(s)"
    },
    {
        index: 2,
        image: "../images/instagram.png",
        title: "Digital Marketing",
        rate: '$900-1200/m',
        av: "Part Time",
        companyName: "Instagram",
        location: "USA",
        vacancy: "08",
        hours: "35h / Week",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis, sunt aut odit voluptatibus accusantium sed iste ipsum voluptas error similique enim sequi ea! Sed officia tenetur, commodi provident possimus a sapiente? Ducimus repudiandae illum porro? Fugiat sed facilis iusto sapiente aperiam ratione ut sequi laborum laboriosam, optio soluta consequatur perferendis praesentium! Inventore exercitationem ullam accusantium incidunt sit pariatur facilis asperiores natus excepturi quos esse quidem eos odit dolores fuga ipsum reprehenderit cupiditate deleniti deserunt, debitis vel voluptate ducimus. Error tempora necessitatibus repudiandae vero ullam illum vel quisquam corporis hic voluptatem sit pariatur minus corrupti inventore, adipisci ex unde esse quaerat. Est, illum voluptates aut cumque id hic placeat sunt natus, non iusto ea aliquam dignissimos quas accusantium assumenda eius minus.",
        workplace: "On-site",
        education: "Bachelor degree in any Computer Science.",
        experience: "2 to 5 year(s)"
    },
    {
        index: 3,
        image: "../images/wordpress.png",
        title: "Freelancer",
        rate: '$900-1000/m',
        av: "Full Time",
        companyName: "Wordpress",
        location: "USA",
        vacancy: "03",
        hours: "40h / Week",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis, sunt aut odit voluptatibus accusantium sed iste ipsum voluptas error similique enim sequi ea! Sed officia tenetur, commodi provident possimus a sapiente? Ducimus repudiandae illum porro? Fugiat sed facilis iusto sapiente aperiam ratione ut sequi laborum laboriosam, optio soluta consequatur perferendis praesentium! Inventore exercitationem ullam accusantium incidunt sit pariatur facilis asperiores natus excepturi quos esse quidem eos odit dolores fuga ipsum reprehenderit cupiditate deleniti deserunt, debitis vel voluptate ducimus. Error tempora necessitatibus repudiandae vero ullam illum vel quisquam corporis hic voluptatem sit pariatur minus corrupti inventore, adipisci ex unde esse quaerat. Est, illum voluptates aut cumque id hic placeat sunt natus, non iusto ea aliquam dignissimos quas accusantium assumenda eius minus.",
        workplace: "On-site",
        education: "Bachelor degree in any Computer Science.",
        experience: "2 to 5 year(s)"
    },
    {
        index: 4,
        image: "../images/yahoo.png",
        title: "User Exeperience",
        rate: '$900-1000/m',
        av: "Full Time",
        companyName: "Yahoo",
        location: "USA",
        vacancy: "04",
        hours: "40h / Week",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis, sunt aut odit voluptatibus accusantium sed iste ipsum voluptas error similique enim sequi ea! Sed officia tenetur, commodi provident possimus a sapiente? Ducimus repudiandae illum porro? Fugiat sed facilis iusto sapiente aperiam ratione ut sequi laborum laboriosam, optio soluta consequatur perferendis praesentium! Inventore exercitationem ullam accusantium incidunt sit pariatur facilis asperiores natus excepturi quos esse quidem eos odit dolores fuga ipsum reprehenderit cupiditate deleniti deserunt, debitis vel voluptate ducimus. Error tempora necessitatibus repudiandae vero ullam illum vel quisquam corporis hic voluptatem sit pariatur minus corrupti inventore, adipisci ex unde esse quaerat. Est, illum voluptates aut cumque id hic placeat sunt natus, non iusto ea aliquam dignissimos quas accusantium assumenda eius minus.",
        workplace: "On-site",
        education: "Bachelor degree in any Computer Science.",
        experience: "2 to 5 year(s)"
    },
    {
        index: 5,
        image: "../images/facebook.png",
        title: "Web Developer",
        rate: '$900-1200/m',
        av: "Full Time",
        companyName: "Facebook",
        location: "USA",
        vacancy: "07",
        hours: "40h / Week",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis, sunt aut odit voluptatibus accusantium sed iste ipsum voluptas error similique enim sequi ea! Sed officia tenetur, commodi provident possimus a sapiente? Ducimus repudiandae illum porro? Fugiat sed facilis iusto sapiente aperiam ratione ut sequi laborum laboriosam, optio soluta consequatur perferendis praesentium! Inventore exercitationem ullam accusantium incidunt sit pariatur facilis asperiores natus excepturi quos esse quidem eos odit dolores fuga ipsum reprehenderit cupiditate deleniti deserunt, debitis vel voluptate ducimus. Error tempora necessitatibus repudiandae vero ullam illum vel quisquam corporis hic voluptatem sit pariatur minus corrupti inventore, adipisci ex unde esse quaerat. Est, illum voluptates aut cumque id hic placeat sunt natus, non iusto ea aliquam dignissimos quas accusantium assumenda eius minus.",
        workplace: "On-site",
        education: "Bachelor degree in any Computer Science.",
        experience: "2 to 5 year(s)"
    },
    {
        index: 5,
        image: "../images/apple.png",
        title: "Product Designer",
        rate: '$700-1200/m',
        av: "Full Time",
        companyName: "Apple",
        location: "USA",
        vacancy: "10",
        hours: "40h / Week",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis, sunt aut odit voluptatibus accusantium sed iste ipsum voluptas error similique enim sequi ea! Sed officia tenetur, commodi provident possimus a sapiente? Ducimus repudiandae illum porro? Fugiat sed facilis iusto sapiente aperiam ratione ut sequi laborum laboriosam, optio soluta consequatur perferendis praesentium! Inventore exercitationem ullam accusantium incidunt sit pariatur facilis asperiores natus excepturi quos esse quidem eos odit dolores fuga ipsum reprehenderit cupiditate deleniti deserunt, debitis vel voluptate ducimus. Error tempora necessitatibus repudiandae vero ullam illum vel quisquam corporis hic voluptatem sit pariatur minus corrupti inventore, adipisci ex unde esse quaerat. Est, illum voluptates aut cumque id hic placeat sunt natus, non iusto ea aliquam dignissimos quas accusantium assumenda eius minus.",
        workplace: "On-site",
        education: "Bachelor degree in any Computer Science.",
        experience: "2 to 5 year(s)"
    },
    {
        index: 5,
        image: "../images/linkedin.png",
        title: "Business Associate",
        rate: '$700-1200/m',
        av: "Part Time",
        companyName: "Linkedin",
        location: "USA",
        vacancy: "10",
        hours: "40h / Week",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis, sunt aut odit voluptatibus accusantium sed iste ipsum voluptas error similique enim sequi ea! Sed officia tenetur, commodi provident possimus a sapiente? Ducimus repudiandae illum porro? Fugiat sed facilis iusto sapiente aperiam ratione ut sequi laborum laboriosam, optio soluta consequatur perferendis praesentium! Inventore exercitationem ullam accusantium incidunt sit pariatur facilis asperiores natus excepturi quos esse quidem eos odit dolores fuga ipsum reprehenderit cupiditate deleniti deserunt, debitis vel voluptate ducimus. Error tempora necessitatibus repudiandae vero ullam illum vel quisquam corporis hic voluptatem sit pariatur minus corrupti inventore, adipisci ex unde esse quaerat. Est, illum voluptates aut cumque id hic placeat sunt natus, non iusto ea aliquam dignissimos quas accusantium assumenda eius minus.",
        workplace: "On-site",
        education: "Bachelor degree in any Computer Science.",
        experience: "2 to 5 year(s)"
    }
];